




@startuml
left to right direction
title 画面遷移図

state トップページ {
}

state マイページ {
    ユーザ情報変更画面 -down-> ユーザ情報変更完了画面
}

state 質問投稿フォーム {
    投稿 -down-> 投稿完了
}

state 報告フォーム {
    報告 -down-> 報告完了
}

トップページ -down-> マイページ
トップページ -down-> ログイン画面
トップページ -down-> 質問投稿フォーム
トップページ -down-> 質問ページ
トップページ -down-> ユーザ登録画面
トップページ -down-> ログアウト画面

マイページ -down-> 質問ページ

ログイン画面 -down-> ユーザ登録画面

質問投稿フォーム -down-> マイページ

質問ページ -down-> 報告フォーム


@enduml