' ローカルルール
'     主キーは -- で区切る
'     * 必須キー
'     <PK> 主キー
'     <FK> 外部キー
'     <A> AUTO INCREMENT
'     <C> チェック（条件も記載）
'     <N> NOT NULL
'     <U> ユニークキー（一意）
'     カラム名 : 型 : 説明 :制約を書く

'表記方法
'コード上で Alt＋D

@startuml test
 hide circle
 skinparam linetype ortho

  entity "user" as user {
     * id   :   int    :    ユーザID    :   <PK><A>
     --
     * name :   varchar(30) :   ユーザ名    :   <N><U>
    <C 空白を含まない>
     * password :   varchar(30) :   パスワード  :   <N><C 空白を含まない>
     is_vicious :   boolean :   悪質なユーザかどうか    : 
 }

  entity "question" as question {
     * id   :   int :   質問ID  :   <PK><A>
     --
     * user_id  : int   : ユーザーID(質問者)    :   <FK>
     * title    :   varchar(30) :   題名    :   <N><U>
     * content    :   text :   質問内容    :   <N>
     * best_answer_id    :   int :   ベストアンサーに選んだ回答ID    :  <FK>
     created_at :   date    :   投稿日時    :   <N>
 }

  entity "answer" as answer {
     * id   :   int :   回答ID  :   <PK><A>
     --
     * user_id  : int   : ユーザーID(回答者)    :   <FK>
     * question_id  : int   : 質問ID    :   <FK>
     * content    :   text :   回答内容    :   <N>
     created_at :   date    :   回答日時    :   <N>
 }

   entity "report" as report {
     * id   :   int :   通報ID  :   <PK><A>
     --
     * reporter_user_id  : int   : 通報したユーザID    :   <FK>
     * reported_user_id  : int   : 通報されたユーザID    :   <FK>
     * content    :   text :   通報理由    :   <N>
     created_at :   date    :   通報日時    :   <N>
 }

 '文法
 '|o：0か1
 '||：1のみ
 '}o：0以上
 '}|：1以上

 user ||..o{ question
 user ||..o{ answer
 question ||..o{ answer
 user ||..o{ report

 @enduml